### ISSUE TITLE
Recommended Addition: First Generation Student

### ISSUE THREAD

**Issue by CaliStringer** [CEDStandards/CEDS-Elements#248] opened 2021-01-14 18:26 UTC
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
Cali Stringer

**Authoring Organization(s)**

CEDS Postsecondary Workgroup, External Review Committee

**Email address**
CStringer@CrocusLLC.com

**Use Case Title**
First Generation Student 

**Use Case Description** 
First Generation Student Status
Yes/No

**Use Case Background**
Indicator of whether individual is a first generation college student.

Higher Education Act of 1965 and 1998, defines a first generation college student as a student both of whose parents did not complete a bachelor’s degree, or in the case of students who live with and are supported by only one parent, a student whose only such parent did not complete a bachelor’s degree

Identified through a review of Ed-Fi’s TPDM. 

**Location of Element in the Domain Entity Schema**
Postsecondary->PS Student->Demographic

**Comment by AEMDuaneBrown** [comment] 2021-06-03 18:47
This issue is linked to #229

**Comment by AEMDuaneBrown** [comment] 2021-07-06 13:38
Closing this issue as it is a duplicate of Issue 229.

**Closed by AEMDuaneBrown** 2021-07-06 13:38 UTC
Labels: duplicate
