### ISSUE TITLE
Update Homeless elements to match EDFacts

### ISSUE THREAD

**Issue by emilycrang** [CEDStandards/CEDS-Elements#809] opened 2023-12-01 19:03 UTC
This is for capturing needs not currently supported by the CEDS model.  Please do not send or share actual data as examples in this issue or in attachments. 

**Author(s)**
CEDS EDFacts Work Group

**Authoring Organization(s)**
SEAs belonging to the CEDS EDFacts Work Group

**Email address**
emily.rang@aemcorp.com

**Use Case Title**
Update definition for Homeless Unaccompanied Youth Status and add new usage note; add new usage note to Homelessness Status.

**Use Case Description** 
List the proposed element name(s), definition(s), and/or option set(s).

**Use Case Background**
This proposal updates definitions and adds usage notes that assist users and reporters of these data in understanding purpose and intent of the information from these elements.

**Location of Element in the Domain Entity Schema**

**Comment by AEMDuaneBrown** [comment] 2023-12-04 15:15
Duplicate of Issue #807 
Closing

**Closed as completed by AEMDuaneBrown** 2023-12-04 15:15 UTC
